# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d35acacbed4542edd80909fd65fdcb7e2435823bee3cd828ea0a44c47d5909ecc42a5be06384710617b8d9c4048ea67a678eeaab6b2ff5c78ab90523e1cf2b59

test:
  secret_key_base: 52967ac4703940b5a9e08a6481b709383d3616e8f1c169c3b53f9c19f8a4765a36f4412a6abead97ff3c681728093284e78af5d098081df70c29c33866ba60ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
